# Default values for snmp-notifier.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: maxwo/snmp-notifier
  tag: v0.3.0
  pullPolicy: IfNotPresent
  spec:
    containers:
      containerPort: 9464
      snmpCommunity: "public"
      # alert.severities is related to severity labels assigned to alerts in
      # alert-rules and should be matched with each other.
      args:
        web.listen-address: :9464
        snmp.trap-description-template: /etc/snmp_notifier/description-template.tpl
        log.format: "logger:stdout?json=true"
        log.level: "debug"
        snmp.destination: 172.17.0.12:162
        snmp.retries: 1
        snmp.trap-oid-label: "oid"
        snmp.trap-default-oid: "1.3.6.1.4.1.1664.1"
        alert.severity-label: "severity"
        alert.severities: "critical,major,minor,warning,info,clear"
        alert.default-severity: "critical"

service:
  type: ClusterIP
  port: 9464
  targetPort: 9464

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as
  # a conscious choice for the user. This also increases chances charts run on
  # environments with little resources, such as Minikube. If you do want to
  # specify resources, uncomment the following lines, adjust them as necessary,
  # and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
