apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
data:
  application.properties: {{ toYaml .Values.configmap.properties | indent 4 }} 
  metrics.yaml: {{ toYaml .Values.configmap.metrics | indent 4 }} 